# Example learning task, we report the lines of code needed to perform a PCA followed by a SVM classification. 
# In particular, we detail the operational steps needed to project the samples of a UCI5 dataset on the cartesian plane 
# generated by the first two principal components, to train a kernel SVM on the projected data and to test 
# the trained model on the same data. 
#
# The dataset chosen for this dimensionality reduction example is the Iris dataset, collecting 150 observations 
# of 3 different classes of iris flowers, each described by 4 attributes. 
# As a working example illustrating the use of the library in a simple machine 

##http://www.researchgate.net/publication/221667696_mlpy_Machine_Learning_Python

iris.shape                               # 2d numpy array, 150 observations and 4 attributes (150, 4) 
import mlpy                              # import the mlpy module 
pca = mlpy.PCA()                         # build a new PCA instance 
pca.learn(iris)                          # perform the PCA on the Iris dataset 
iris_pc = pca.transform(iris, k=2)       # project Iris on the first 2 PCs 
svm = mlpy.LibSvm(kernel_type=’linear’)  # build a new LibSVM instance 
svm.learn(iris_pc, labels)               # train the model 
labels_pred = svm.pred(iris_pc)          # test the model 
mlpy.error(labels, labels_pred)          # compute the prediction error 
